name: dependencies
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies: 
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
 
  intl: ^0.17.0
  get_it: ^7.2.0
  equatable: ^2.0.3
  dio: ^4.0.6
  flutter_bloc: ^8.0.1
  go_router: ^5.1.1
  candlesticks: ^2.1.0

flutter:


